### ISSUE TITLE
html-to-epub3: `nav` element with `epub:type="toc"` should have `role="doc-toc"` according to Ace

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-modules#78]
Issue reported by Tom McCartney:

> In the toc.xhtml document that is being generated by the html-to-epub3 transformation, there is a "nav" element created with an epub:type="toc" attribute.  Ace is complaining that the element should also have an Aria Role element associated with it.  When I ran into this last year, I found that adding a role="doc-toc" attribute to that nav element would stop the complaint in ACE.  But last year I was using an older version of Pipeline 2 and I had access to the .jar files to be able to tweak the XSLT translation to add the role to make ACE happy.  Using the 1.14.17-p1 release of the Pipeline App, since it's a complied EXE, I don't have that ability.  (I did try to pull the source and build it on my Windows 10 machine based upon the Build System docs from the GitHub docs, but that didn't go so well.)

**Comment by GrayWolfMT** [comment]
I'm attaching an example ePub with the original HTML file and the ACE output report.
[General-Source.zip](https://github.com/daisy/pipeline-modules/files/14561062/General-Source.zip)
[General-ePub.zip](https://github.com/daisy/pipeline-modules/files/14561071/General-ePub.zip)
[General-Report.zip](https://github.com/daisy/pipeline-modules/files/14561073/General-Report.zip)
